### ISSUE TITLE
Pip package do not work properly

### ISSUE THREAD

**Issue by freQuensy23-coder** [aweone/CryptoPayAPI#1]
I've installed this api wrapper using pip (`pip install CryptoPayAPI` ). But it is not working. For example:

```
from CryptoPayAPI.CryptoPay import CryptoPay
from CryptoPayAPI.types import Asset
```

Will raise `ModuleNotFoundError: No module named 'CryptoPayAPI.types'`. 
The directory with the installed cryptobot is half empty:
/venv/Lib/site-packages/CryptoPayAPI contains only __init__.py file with this content: 
```
from .types import *
from .exceptions import *

__version__ = "0.0.2"
```

**Comment by aweone** [comment]
Fixed. Thx, great job!
